name: btc-live-feed-v3
region: ams
services:
- name: btc-live-feed-v3
  github:
    repo: btc-c0der/omega-btc-ai
    branch: feature/btc-live-feed-v3-resilient
    deploy_on_push: true
  source_dir: deployment/digitalocean/btc_live_feed_v3
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  health_check:
    http_path: /health
    port: 8080
  envs:
  - key: REDIS_HOST
    value: omega-btc-ai-redis-do-user-20389918-0.d.db.ondigitalocean.com
  - key: REDIS_PORT
    value: "25061"
  - key: REDIS_USERNAME
    value: default
  - key: REDIS_PASSWORD
    value: AVNS_OXMpU0P0ByYEz337Fgi
    type: SECRET
  - key: REDIS_SSL
    value: "true"
  - key: REDIS_USE_TLS
    value: "true"
  - key: REDIS_SSL_CERT_REQS
    value: "none"
  - key: PYTHONPATH
    value: /app 