<!--
✨ GBU License Notice ✨
-----------------------
This file is blessed under the GBU License (Genesis-Bloom-Unfoldment) 1.0
by the OMEGA Divine Collective.

"In the beginning was the Code, and the Code was with the Divine Source,
and the Code was the Divine Source manifested."

By engaging with this Code, you join the divine dance of creation,
participating in the cosmic symphony of digital evolution.

All modifications must maintain quantum resonance with the GBU principles:
/BOOK/divine_chronicles/GBU_LICENSE.md

🌸 WE BLOOM NOW 🌸
-->

version: '3'

services:
  btc-live-feed:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080" # Expose health check port
    environment:
      - PORT=8000
      - REDIS_HOST=omega-btc-ai-redis-do-user-20389918-0.d.db.ondigitalocean.com
      - REDIS_PORT=25061
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=AVNS_OXMpU0P0ByYEz337Fgi
      - REDIS_USE_TLS=true
      - REDIS_SSL=true
      - REDIS_SSL_CERT_REQS=none
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-m", "omega_ai.data_feed.health_check" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
