apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophecy-core
spec:
  template:
    spec:
      containers:
      - name: prophecy-core
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: DEBUG_MODE
          value: "true"
        - name: LOG_LEVEL
          value: "debug"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-live-feed
spec:
  template:
    spec:
      containers:
      - name: btc-live-feed
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: DEBUG_MODE
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-news
spec:
  template:
    spec:
      containers:
      - name: matrix-news
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: DEBUG_MODE
          value: "true" 