apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: omega-btc-ai-dev

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-ingress.yaml

commonLabels:
  environment: dev 