apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-news
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-live-feed
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophecy-core
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1 