apiVersion: v1
kind: ConfigMap
metadata:
  name: port-forward-config
  namespace: omega-grid-dev
data:
  services.json: |
    {
      "kubernetes-dashboard": {
        "namespace": "kubernetes-dashboard",
        "localPort": 8443,
        "targetPort": 443
      },
      "cli-portal": {
        "namespace": "omega-grid-dev",
        "localPort": 2222,
        "targetPort": 22
      },
      "nft-services": {
        "namespace": "omega-grid-dev",
        "localPort": 8080,
        "targetPort": 8080
      }
    } 