apiVersion: v1
kind: ServiceAccount
metadata:
  name: divine-port-forward
  namespace: omega-grid-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: divine-port-forward
rules:
- apiGroups: [""]
  resources: ["services", "pods", "services/portforward", "pods/portforward"]
  verbs: ["get", "list", "watch", "create"]
  # Allow access to all namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: divine-port-forward
subjects:
- kind: ServiceAccount
  name: divine-port-forward
  namespace: omega-grid-dev
roleRef:
  kind: ClusterRole
  name: divine-port-forward
  apiGroup: rbac.authorization.k8s.io 