version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - ./redis_data:/data
      - ./tools/redis.conf.optimized:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-omega_db}
      POSTGRES_USER: ${POSTGRES_USER:-omega_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-omega_pass}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omega_user -d omega_db"]
      interval: 5s
      timeout: 3s
      retries: 3

  omega_btc_ai:
    build: .
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8765:8765"  # WebSocket Server
      - "8050:8050"  # Dashboard UI
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - LOG_LEVEL=${LOG_LEVEL:-INFO}