version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3

  trap-probability-meter:
    build:
      context: .
      dockerfile: docker/TrapProbabilityMeter.Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=false
      - INTERVAL=5
    restart: unless-stopped

  trap-aware-traders:
    build:
      context: .
      dockerfile: docker/TrapAwareTraders.Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USE_TESTNET=true
      - SYMBOL=BTCUSDT
      - LONG_CAPITAL=24.0
      - SHORT_CAPITAL=24.0
      - TRAP_PROBABILITY_THRESHOLD=0.7
      - TRAP_ALERT_THRESHOLD=0.8
      - ENABLE_TRAP_PROTECTION=true
      - ENABLE_ELITE_EXITS=true
      - ELITE_EXIT_CONFIDENCE=0.7
    volumes:
      - ./config:/app/config
    restart: unless-stopped

  divine-dashboard:
    build:
      context: .
      dockerfile: docker/DivineDashboard.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
