version: '3.8'

# OMEGA BTC AI - Trap-Aware Dual Traders (TADT) System
# Scaleway Cloud Deployment Configuration
# This configuration uses the existing Scaleway Cloud Redis instance
# Now with Fibonacci aligned architecture (1,1,2,3,5)

services:
  trap-probability-meter:
    build:
      context: .
      dockerfile: docker/TrapProbabilityMeter.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DEBUG=false
      - INTERVAL=5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trap-aware-traders:
    build:
      context: .
      dockerfile: docker/TrapAwareTraders.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - USE_TESTNET=${USE_TESTNET:-true}
      - SYMBOL=${SYMBOL:-BTCUSDT}
      - LONG_CAPITAL=${LONG_CAPITAL:-24.0}
      - SHORT_CAPITAL=${SHORT_CAPITAL:-24.0}
      - TRAP_PROBABILITY_THRESHOLD=${TRAP_PROBABILITY_THRESHOLD:-0.7}
      - TRAP_ALERT_THRESHOLD=${TRAP_ALERT_THRESHOLD:-0.8}
      - ENABLE_TRAP_PROTECTION=${ENABLE_TRAP_PROTECTION:-true}
      - ENABLE_ELITE_EXITS=${ENABLE_ELITE_EXITS:-true}
      - ELITE_EXIT_CONFIDENCE=${ELITE_EXIT_CONFIDENCE:-0.7}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - API_PASSPHRASE=${API_PASSPHRASE}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  elite-exit-strategy:
    build:
      context: .
      dockerfile: docker/EliteExitStrategy.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SYMBOL=${SYMBOL:-BTCUSDT}
      - CONFIDENCE_THRESHOLD=${ELITE_EXIT_CONFIDENCE:-0.7}
      - ENABLE_FIBONACCI_EXITS=${ENABLE_FIBONACCI_EXITS:-true}
      - ENABLE_PATTERN_RECOGNITION=${ENABLE_PATTERN_RECOGNITION:-true}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "4"

  divine-dashboard:
    build:
      context: .
      dockerfile: docker/DivineDashboard.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - divine-dashboard
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
