from setuptools import setup, find_packages

setup(
    name="omega-btc-ai",
    version="0.420",
    packages=find_packages(),
    install_requires=[
        "flask",
        "flask-cors",
        "flask-socketio",
        "gevent-websocket",
        "redis",
        "ccxt",
        "plotly",
        "numpy",
        "pandas",
        "torch",
        "diffusers",
        "transformers",
        "accelerate",
        "pillow",
        "websockets",
        "fastapi",
        "uvicorn",
        "cryptography"
    ],
    author="OMEGA BTC AI DIVINE COLLECTIVE",
    author_email="divine@omega-btc-ai.com",
    description="Advanced Bitcoin market analysis system with real-time trend tracking and market maker trap detection",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/omega-btc-ai",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GPU License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
    license="GPU License",
) 