name: omega-btc-ai-live-feed-v3
region: nyc
services:
  - name: btc-live-feed-v3
    github:
      repo: btc-c0der/omega-btc-ai
      branch: feature/btc-live-feed-v3-resilient
      deploy_on_push: true
    build_command: pip install -e .
    run_command: python -m omega_ai.data_feed.btc_live_feed_v3
    envs:
      - key: REDIS_HOST
        value: ${redis.HOSTNAME}
        scope: RUN_TIME
      - key: REDIS_PORT
        value: ${redis.PORT}
        scope: RUN_TIME
      - key: REDIS_USERNAME
        value: ${redis.USERNAME}
        scope: RUN_TIME
      - key: REDIS_PASSWORD
        value: ${redis.PASSWORD}
        scope: RUN_TIME
      - key: REDIS_USE_SSL
        value: "true"
        scope: RUN_TIME
      - key: FAILOVER_REDIS_HOST
        value: "localhost"
        scope: RUN_TIME
      - key: FAILOVER_REDIS_PORT
        value: "6379"
        scope: RUN_TIME
      - key: HEALTH_CHECK_PORT
        value: "8080"
        scope: RUN_TIME
      - key: HEALTH_CHECK_HOST
        value: "0.0.0.0"
        scope: RUN_TIME
    health_check:
      http_path: /health
      port: 8080
    resources:
      instance_size: basic-xs
      instance_count: 1
    routes:
      - path: /health
      - path: /metrics
      - path: /redis/status
    alerts:
      - rule: DEPLOYMENT_FAILED
      - rule: DOMAIN_FAILED
      - rule: CPU_UTILIZATION
        value: 90
        window: FIVE_MINUTES
        operator: GREATER_THAN
      - rule: MEM_UTILIZATION
        value: 90
        window: FIVE_MINUTES
        operator: GREATER_THAN

  - name: btc-live-feed-v3-health
    github:
      repo: btc-c0der/omega-btc-ai
      branch: feature/btc-live-feed-v3-resilient
      deploy_on_push: true
    build_command: pip install -e .
    run_command: python -m omega_ai.data_feed.health_check
    envs:
      - key: REDIS_HOST
        value: ${redis.HOSTNAME}
        scope: RUN_TIME
      - key: REDIS_PORT
        value: ${redis.PORT}
        scope: RUN_TIME
      - key: REDIS_USERNAME
        value: ${redis.USERNAME}
        scope: RUN_TIME
      - key: REDIS_PASSWORD
        value: ${redis.PASSWORD}
        scope: RUN_TIME
      - key: REDIS_USE_SSL
        value: "true"
        scope: RUN_TIME
      - key: HEALTH_CHECK_PORT
        value: "8080"
        scope: RUN_TIME
      - key: HEALTH_CHECK_HOST
        value: "0.0.0.0"
        scope: RUN_TIME
    routes:
      - path: /
    resources:
      instance_size: basic-xs
      instance_count: 1

databases:
  - name: redis
    engine: redis
    production: true
    version: "6.2"
    cluster_name: omega-btc-ai-redis
    db_name: btc-live-feed
    db_user: default 