# OMEGA Pro Surfer Sample Configuration
# ====================================

# API Configuration
api:
  exchange: "bitget"
  testnet: true
  api_key: "YOUR_API_KEY"
  api_secret: "YOUR_API_SECRET"
  passphrase: "YOUR_PASSPHRASE"  # Only for exchanges that require it

# Trading Parameters
trading:
  market: "BTC/USDT"
  strategy: "quantum_divergence"
  timeframe: "1h"
  position_size: 0.01  # BTC
  max_open_positions: 3
  stop_loss_pct: 2.5
  take_profit_pct: 5.0

# Quantum Neural Network Settings
quantum:
  enabled: true
  celebration_cycles: 5
  quantum_depth: 3
  entanglement_level: "medium"  # low, medium, high
  calibration_interval: 24  # hours

# Notification Settings
notifications:
  telegram:
    enabled: true
    bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
    chat_id: "YOUR_TELEGRAM_CHAT_ID"
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    sender: "bot@example.com"
    recipient: "you@example.com"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "omega_surf.log"
  rotation: "daily"  # hourly, daily, weekly

# Backtest Settings (for strategy development)
backtest:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_balance: 10000  # USDT
  fee_rate: 0.001  # 0.1% 