#!/usr/bin/env python3
"""
Quantum 5D QA Dashboard Application
---------------------------------

This module provides the main Dash application for the Quantum 5D QA Dashboard.
"""

import os
import sys
import logging
import dash
import dash_bootstrap_components as dbc
from dash import html, dcc
from pathlib import Path

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("Quantum5DQADashboard")

# Import dashboard modules
from .config import DASHBOARD_CONFIG, CUSTOM_CSS, CUSTOM_DASH_INDEX_STRING
from .layout import create_dashboard_layout
from .callbacks import register_callbacks
from .connection import ConnectionManager


def create_app(custom_port=None):
    """Create and configure Dash application.
    
    Args:
        custom_port: Optional port to use instead of default
        
    Returns:
        Configured Dash application
    """
    # Set up assets folder
    current_dir = Path(__file__).parent
    assets_path = current_dir / "assets"
    assets_path.mkdir(exist_ok=True)
    
    # Create CSS file if it doesn't exist
    css_file = assets_path / "styles.css"
    if not css_file.exists():
        with open(css_file, "w") as f:
            f.write(CUSTOM_CSS)
    
    # Create connection manager
    conn_manager = ConnectionManager(default_port=custom_port or DASHBOARD_CONFIG["port"])
    
    # Create Dash app
    app = dash.Dash(
        __name__,
        assets_folder=str(assets_path),
        external_stylesheets=[dbc.themes.DARKLY],
        index_string=CUSTOM_DASH_INDEX_STRING,
        suppress_callback_exceptions=True,  # Suppress exceptions for callbacks to components generated by other callbacks
        title="Quantum 5D QA Dashboard"
    )
    
    # Set up layout
    app.layout = create_dashboard_layout()
    
    # Register callbacks
    register_callbacks(app)
    
    # Interval component for periodic updates
    app.layout.children.append(
        dcc.Interval(
            id="metrics-interval",
            interval=DASHBOARD_CONFIG["ui_refresh_interval"] * 1000,  # Convert to milliseconds
            n_intervals=0
        )
    )
    
    # Store components for state
    app.layout.children.extend([
        dcc.Store(id="metrics-store", data={}),
        dcc.Store(id="test-runner-store", data={})
    ])
    
    return app, conn_manager


def run_app(host='0.0.0.0', port=8051, debug=False, open_browser=False):
    """Run the Dash application with automatic port detection.
    
    Args:
        host: Host IP to listen on
        port: Port to try using (will auto-detect if taken)
        debug: Whether to run in debug mode
        open_browser: Whether to open the dashboard in a browser
    """
    # Create connection manager for auto port detection
    connection = ConnectionManager(host=host, port=port)
    host, port = connection.get_connection_info()
    
    # Create app
    app, conn_manager = create_app()
    
    # Print connection information
    connection.print_connection_info()
    
    # Open in browser if requested
    if open_browser:
        connection.open_dashboard()
    
    # Run server
    try:
        app.run(host=host, port=port, debug=debug)
    except OSError as e:
        if "Address already in use" in str(e):
            logger.error(f"Port {port} is already in use. Please try a different port.")
            sys.exit(1)
        else:
            raise


if __name__ == '__main__':
    # Get port from command line args
    port = 8051
    if len(sys.argv) > 1:
        try:
            port = int(sys.argv[1])
        except ValueError:
            logger.warning(f"Invalid port: {sys.argv[1]}. Using default port 8051.")
    
    # Run app
    run_app(port=port) 