# 🔱 OMEGA BTC AI - Divine Development Environment 🔱

version: '3.8'

services:
  # 🔍 Development Tools
  dev-tools:
    image: alpine:latest
    container_name: omega_dev_tools
    volumes:
      - ../:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - ${DOCKER_NETWORK}
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '${SERVICE_CPU_LIMIT}'
          memory: ${SERVICE_MEMORY_LIMIT}
    restart: unless-stopped

  # 📊 Development Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: omega_prometheus
    volumes:
      - ./infra/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    deploy:
      resources:
        limits:
          cpus: '${SERVICE_CPU_LIMIT}'
          memory: ${SERVICE_MEMORY_LIMIT}
    restart: unless-stopped

  # 📈 Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: omega_grafana
    volumes:
      - ./infra/monitoring/grafana:/var/lib/grafana
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - ${DOCKER_NETWORK}
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    deploy:
      resources:
        limits:
          cpus: '${SERVICE_CPU_LIMIT}'
          memory: ${SERVICE_MEMORY_LIMIT}
    restart: unless-stopped

  # 🔍 Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: omega_jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "${JAEGER_UI_PORT}:16686"
      - "${JAEGER_COLLECTOR_PORT}:14250"
    volumes:
      - jaeger_data:/var/lib/jaeger
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:16686/api/traces" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    deploy:
      resources:
        limits:
          cpus: '${SERVICE_CPU_LIMIT}'
          memory: ${SERVICE_MEMORY_LIMIT}
    restart: unless-stopped

  # 📝 Development Documentation
  docs:
    image: docsify-cli:latest
    container_name: omega_docs
    volumes:
      - ./docs:/docs
    ports:
      - "${DOCS_PORT}:3000"
    networks:
      - ${DOCKER_NETWORK}
    command: docsify serve /docs
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000" ]
      interval: ${HEALTH_CHECK_INTERVAL}
      timeout: ${HEALTH_CHECK_TIMEOUT}
      retries: ${HEALTH_CHECK_RETRIES}
    deploy:
      resources:
        limits:
          cpus: '${SERVICE_CPU_LIMIT}'
          memory: ${SERVICE_MEMORY_LIMIT}
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  jaeger_data:
    driver: local
