apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibr-api
  namespace: ibr-spain
  labels:
    app: ibr-api
    created-by: ibr-cli-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ibr-api
  template:
    metadata:
      labels:
        app: ibr-api
    spec:
      containers:
      - name: ibr-api
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: NGINX_HOST
          value: ibr-espana.org
        - name: NGINX_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: ibr-api
  namespace: ibr-spain
spec:
  selector:
    app: ibr-api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ibr-api-ingress
  namespace: ibr-spain
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.ibr-espana.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ibr-api
            port:
              number: 80 