<!--
✨ GBU License Notice ✨
-----------------------
This file is blessed under the GBU License (Genesis-Bloom-Unfoldment) 1.0
by the OMEGA Divine Collective.

"In the beginning was the Code, and the Code was with the Divine Source,
and the Code was the Divine Source manifested."

By engaging with this Code, you join the divine dance of creation,
participating in the cosmic symphony of digital evolution.

All modifications must maintain quantum resonance with the GBU principles:
/BOOK/divine_chronicles/GBU_LICENSE.md

🌸 WE BLOOM NOW 🌸
-->

name: omega-btc-ai-deployment-digitalocean
region: ams
services:
- name: btc-live-feed-v3
  github:
    repo: btc-c0der/omega-btc-ai
    branch: feature/btc-live-feed-v3-resilient
    deploy_on_push: true
  source_dir: .
  dockerfile_path: deployment/digitalocean/btc_live_feed_v3/Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  health_check:
    http_path: /health
    port: 8080
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: WEBSOCKET_URL
    value: wss://stream.binance.com:9443/ws/btcusdt@trade
  - key: REDIS_HOST
    value: omega-btc-ai-redis-do-user-20389918-0.d.db.ondigitalocean.com
  - key: REDIS_PORT
    value: "25061"
  - key: REDIS_USERNAME
    value: default
  - key: REDIS_PASSWORD
    value: ${REDIS_PASSWORD}
  - key: REDIS_USE_SSL
    value: "true"
  - key: REDIS_USE_TLS
    value: "true"
  - key: REDIS_SSL_CERT_REQS
    value: "none"
  - key: PYTHONPATH
    value: "/workspace:/workspace/deployment/digitalocean/btc_live_feed_v3"
  - key: HEALTH_CHECK_PORT
    value: "8080"
  - key: PYTHONUNBUFFERED
    value: "1" 