version: '3.8'

services:
  news-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: omega-btc-ai/news-service:latest
    environment:
      - PYTHONPATH=/app
      - PORT=8080
      - NEWS_SERVICE_PORT=8080
    volumes:
      - ./BOOK:/app/BOOK
      - ./scripts:/app/scripts
      - ./data:/workspace/data
    command: python /app/scripts/api_server.py
    networks:
      - news-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    ports:
      - "10082:80"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - news-service
    networks:
      - news-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  news-network:
    driver: bridge
