version: '3.8'

services:
  news-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: omega-btc-ai/news-service:latest
    environment:
      - PYTHONPATH=/app
      - PORT=8080
    volumes:
      - ./BOOK:/app/BOOK
      - ./scripts:/app/scripts
      - ./data:/workspace/data
    command: python /app/scripts/api_server.py
    networks:
      - news-network

  nginx:
    image: nginx:alpine
    ports:
      - "10082:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - news-service
    networks:
      - news-network

networks:
  news-network:
    driver: bridge
