version: '3'

services:
  news-service:
    build: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./articles:/app/articles
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "10082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
      - nginx_temp:/var/cache/nginx
      - nginx_logs:/var/log/nginx
      - nginx_run:/var/run
    depends_on:
      - news-service
    restart: always
    read_only: true
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/portal/" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first

volumes:
  nginx_temp:
  nginx_logs:
  nginx_run:
