version: '3'

services:
  news-service:
    build: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./articles:/app/articles
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "10082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
    depends_on:
      - news-service
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/portal/" ]
      interval: 30s
      timeout: 10s
      retries: 3
