bot:
  name: CyBer1t4L
  description: Advanced Quality Assurance Bot for OMEGA Trading Ecosystem
  version: 1.0.0

testing:
  coverage_threshold: 80.0
  monitor_components:
    - trading
    - discord
    - matrix
  critical_modules:
    - src/omega_bot_farm/trading/b0ts/ccxt/ccxt_strategic_trader.py
    - src/omega_bot_farm/bitget_positions_info.py
    - src/omega_bot_farm/matrix_cli_live_positions.py
  report_directory: reports
  run_interval_minutes: 60

discord:
  enabled: true
  command_prefix: "!"
  status_message: "Monitoring QA | /qa_status"

monitoring:
  enabled: true
  interval_minutes: 60
  realtime_monitoring: true
  
reporting:
  html_reports: true
  json_reports: true
  console_reports: true
  max_report_age_days: 30
  report_format: "cyberpunk"
