apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: omega-btc-ai
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    rule_files:
      - "/etc/prometheus/rules/*.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'matrix-news'
        static_configs:
        - targets: ['matrix-news:10082']

      - job_name: 'btc-live-feed'
        static_configs:
        - targets: ['btc-live-feed:10081']

      - job_name: 'prophecy-core'
        static_configs:
        - targets: ['prophecy-core:10080']

      - job_name: 'redis'
        static_configs:
        - targets: ['redis:6379']

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: omega-btc-ai
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email-notifications'

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'alerts@example.com'  # Replace with your email
        from: 'alertmanager@example.com'  # Replace with your email
        smarthost: 'smtp.example.com:587'  # Replace with your SMTP server
        auth_username: 'alerts@example.com'  # Replace with your email
        auth_identity: 'alerts@example.com'  # Replace with your email
        auth_password: 'password'  # Replace with your password

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance'] 