apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis.yaml
  - matrix-news.yaml
  - btc-live-feed.yaml
  - prophecy-core.yaml
  - monitoring.yaml
  - ingress.yaml
  - secrets.yaml
  - configmaps.yaml

commonLabels:
  app: omega-btc-ai 