apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - matrix-news.yaml
  - btc-live-feed.yaml
  - prophecy-core.yaml
  - monitoring.yaml
  - ingress.yaml
  - secrets.yaml
  - configmaps.yaml

labels:
  - pairs:
      app: omega-btc-ai 