apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
stringData:
  password: change-me-in-prod  # Replace with actual password in production
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
type: Opaque
stringData:
  admin-password: change-me-in-prod  # Replace with actual password in production 