apiVersion: apps/v1
kind: Deployment
metadata:
  name: prophecy-core
spec:
  template:
    spec:
      containers:
      - name: prophecy-core
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: DEBUG_MODE
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        - name: METRICS_ENABLED
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-live-feed
spec:
  template:
    spec:
      containers:
      - name: btc-live-feed
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: DEBUG_MODE
          value: "false"
        - name: METRICS_ENABLED
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-news
spec:
  template:
    spec:
      containers:
      - name: matrix-news
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: DEBUG_MODE
          value: "false"
        - name: METRICS_ENABLED
          value: "true" 