apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omega-grid-prod

bases:
  - ../../base

resources:
  - namespace.yaml
  - ingress.yaml

patches:
  - path: configmap.yaml
  - path: deployment-patch.yaml

images:
  - name: prophecy-core
    newName: prophecy-core
    newTag: latest
  - name: btc-live-feed
    newName: btc-live-feed
    newTag: latest
  - name: matrix-news
    newName: matrix-news
    newTag: latest

replicas:
  - name: prophecy-core
    count: 3
  - name: btc-live-feed
    count: 2
  - name: matrix-news
    count: 2

# Labels to add to all resources
commonLabels:
  environment: prod

configMapGenerator:
  - name: omega-config
    behavior: merge
    literals:
      - OMEGA_ENV=production
      - LOG_LEVEL=info