apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: omega-btc-ai-prod

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-ingress.yaml
  - patch-resources.yaml

commonLabels:
  environment: prod 