apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: omega-grid-prod

patches:
  - path: patch-replicas.yaml
  - path: patch-ingress.yaml
  - path: patch-resources.yaml

labels:
  - pairs:
      environment: prod