version: '3.8'

# OMEGA BTC AI - Trap-Aware Dual Traders (TADT) System
# Scaleway Cloud Deployment Configuration
# This configuration uses the existing Scaleway Cloud Redis instance

services:
  btc-live-feed:
    build:
      context: .
      dockerfile: docker/BTCLiveFeed.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME:-btc-omega-redis}
      - REDIS_USE_TLS=${REDIS_USE_TLS:-true}
      - REDIS_CERT=${REDIS_CERT:-/app/config/SSL_redis-btc-omega-redis.pem}
      - DEBUG=false
      - USE_GPU=${USE_GPU:-false}
      - TF_FORCE_GPU_ALLOW_GROWTH=${TF_FORCE_GPU_ALLOW_GROWTH:-false}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    restart: unless-stopped
    # GPU support is commented out by default for simpler initial deployment
    # Uncomment the following section after confirming GPU availability
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [ gpu ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trap-probability-meter:
    build:
      context: .
      dockerfile: docker/TrapProbabilityMeter.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DEBUG=false
      - INTERVAL=5
      - USE_GPU=${USE_GPU:-false}
      - TF_FORCE_GPU_ALLOW_GROWTH=${TF_FORCE_GPU_ALLOW_GROWTH:-false}
    # GPU support is commented out by default for simpler initial deployment
    # Uncomment the following section after confirming GPU availability
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [ gpu ]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  trap-aware-traders:
    build:
      context: .
      dockerfile: docker/TrapAwareTraders.Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - USE_TESTNET=${USE_TESTNET:-true}
      - SYMBOL=${SYMBOL:-BTCUSDT}
      - LONG_CAPITAL=${LONG_CAPITAL:-24.0}
      - SHORT_CAPITAL=${SHORT_CAPITAL:-24.0}
      - TRAP_PROBABILITY_THRESHOLD=${TRAP_PROBABILITY_THRESHOLD:-0.7}
      - TRAP_ALERT_THRESHOLD=${TRAP_ALERT_THRESHOLD:-0.8}
      - ENABLE_TRAP_PROTECTION=${ENABLE_TRAP_PROTECTION:-true}
      - ENABLE_ELITE_EXITS=${ENABLE_ELITE_EXITS:-true}
      - ELITE_EXIT_CONFIDENCE=${ELITE_EXIT_CONFIDENCE:-0.7}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - API_PASSPHRASE=${API_PASSPHRASE}
      - USE_GPU=${USE_GPU:-false}
      - TF_FORCE_GPU_ALLOW_GROWTH=${TF_FORCE_GPU_ALLOW_GROWTH:-false}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    # GPU support is commented out by default for simpler initial deployment
    # Uncomment the following section after confirming GPU availability
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [ gpu ]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  divine-dashboard:
    build:
      context: .
      dockerfile: docker/DivineDashboard.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST:-172.16.8.2} # Default to Scaleway Cloud Redis IP
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - USE_GPU=${USE_GPU:-false}
      - TF_FORCE_GPU_ALLOW_GROWTH=${TF_FORCE_GPU_ALLOW_GROWTH:-false}
    # GPU support is commented out by default for simpler initial deployment
    # Uncomment the following section after confirming GPU availability
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [ gpu ]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - divine-dashboard
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
