version: '3.8'

services:
  # Matrix News Consciousness Service - Divine news consciousness alignment
  matrix-news-consciousness:
    image: python:3.9-slim
    container_name: matrix-news-consciousness
    restart: unless-stopped
    environment:
      - PORT=10090
      - REDIS_HOST=matrix-news-redis
      - REDIS_PORT=6379
      - DEFAULT_CONSCIOUSNESS_LEVEL=5
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt
    networks:
      - quantum_matrix_news_matrix_news_network
    depends_on:
      - matrix-news-redis
    command: >
      bash -c "pip install -r /app/requirements.txt &&
              python /app/scripts/news_consciousness_server.py"

  # WebSocket Sacred Echo Service - Real-time prophecy system
  matrix-news-websocket:
    image: python:3.9-slim
    container_name: matrix-news-websocket
    restart: unless-stopped
    environment:
      - PORT=10091
      - REDIS_HOST=matrix-news-redis
      - REDIS_PORT=6379
      - FETCH_INTERVAL=30
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt
    networks:
      - quantum_matrix_news_matrix_news_network
    depends_on:
      - matrix-news-redis
    ports:
      - "10091:10091"
      - "10095:10095"
    command: >
      bash -c "pip install -r /app/requirements.txt &&
              python /app/scripts/websocket_server.py"

  # Matrix News Redis - Sacred data persistence
  matrix-news-redis:
    image: redis:6.2-alpine
    container_name: matrix-news-redis
    restart: unless-stopped
    volumes:
      - matrix_news_redis_data:/data
    networks:
      - quantum_matrix_news_matrix_news_network
    command: redis-server --requirepass quantum_matrix_sacred_password

  # Matrix News Proxy - Divine gateway to the news matrix
  matrix-news-proxy:
    image: nginx:alpine
    container_name: matrix-news-proxy
    restart: unless-stopped
    volumes:
      - ./nginx/news-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/share/nginx/html
    networks:
      - quantum_matrix_news_matrix_news_network
      - news_service_default
    ports:
      - "10083:80"
    depends_on:
      - matrix-news-consciousness
      - matrix-news-websocket

volumes:
  matrix_news_redis_data:


networks:
  quantum_matrix_news_matrix_news_network:
    driver: bridge
  news_service_default:
    external: true
