apiVersion: apps/v1
kind: Deployment
metadata:
  name: omega-prm-miner
  labels:
    app: omega-prm-miner
    component: quantum-mining
spec:
  replicas: 3
  selector:
    matchLabels:
      app: omega-prm-miner
  template:
    metadata:
      labels:
        app: omega-prm-miner
        component: quantum-mining
    spec:
      containers:
      - name: miner
        image: quantum-pow:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "quantum_pow.omega_prm_runner"]
        env:
        - name: MINING_ITERATIONS
          value: "1000"
        - name: MINING_TIME_LIMIT
          value: "30"
        - name: MINING_PARALLELISM
          value: "4"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          name: mining-api
        livenessProbe:
          httpGet:
            path: /health
            port: mining-api
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: mining-api
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: blockchain-data
          mountPath: /app/data
      volumes:
      - name: blockchain-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: omega-prm-miner
  labels:
    app: omega-prm-miner
spec:
  selector:
    app: omega-prm-miner
  ports:
  - port: 8080
    targetPort: mining-api
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: omega-prm-miner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: omega-prm-miner
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: omega-prm-config
data:
  mining-config.json: |
    {
      "difficulty": "0x1f00ffff",
      "reward_address": "quantum_address_default",
      "mining_strategy": {
        "exploration_weight": 1.414,
        "max_tree_depth": 50,
        "simulation_count": 20,
        "prune_threshold": 0.01
      },
      "network": {
        "sync_interval": 5,
        "peer_discovery_enabled": true,
        "max_peers": 10
      },
      "logging": {
        "level": "info",
        "file": "mining.log"
      }
    }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: omega-prm-network-policy
spec:
  podSelector:
    matchLabels:
      app: omega-prm-miner
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: quantum-mining
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          component: quantum-mining
    ports:
    - protocol: TCP
      port: 8080 