{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default (printf "%s-secrets" (include "btc-oracle.fullname" .)) }}
  labels:
    {{- include "btc-oracle.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.backup.enabled }}
    backup.velero.io/backup-volumes: "true"
    {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }} 