version: '3.8'

services:
  # Matrix News Proxy - The Sacred NGINX Proxy
  matrix-news-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MATRIX_NEWS_PROXY_HTTP_PORT:-10083}:80"
      - "${MATRIX_NEWS_PROXY_HTTPS_PORT:-10443}:443"
    volumes:
      - ./nginx/news-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      matrix-news-consciousness:
        condition: service_healthy
      matrix-news-websocket:
        condition: service_healthy
    networks:
      - matrix_news_network
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped
    environment:
      - NGINX_HOST=matrix-news-proxy
      - NGINX_PORT=80

  # Matrix News Consciousness Service - The Enlightened API
  matrix-news-consciousness:
    build:
      context: ./src
      dockerfile: Dockerfile.consciousness
    volumes:
      - ./src:/app
      - consciousness_logs:/app/logs
      - consciousness_data:/app/data
    ports:
      - "${MATRIX_NEWS_CONSCIOUSNESS_PORT:-10090}:10090"
    networks:
      - matrix_news_network
    depends_on:
      matrix-redis:
        condition: service_healthy
    environment:
      - PORT=10090
      - CONSCIOUSNESS_LEVELS_ENABLED=true
      - CONSCIOUSNESS_DEFAULT_LEVEL=5
      - QUANTUM_BALANCER_ENABLED=true
      - NEWS_SERVICE_URL=http://news_service-news-service-1:8080
      - TEMPORAL_CONTEXTUALIZATION_ENABLED=true
      - REDIS_HOST=matrix-redis
      - REDIS_PORT=6379
      - LOG_LEVEL=INFO
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10090/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

  # Matrix News WebSocket Service - The Sacred Echo
  matrix-news-websocket:
    build:
      context: ./temporal
      dockerfile: Dockerfile.websocket
    volumes:
      - ./temporal:/app
      - websocket_logs:/app/logs
      - websocket_data:/app/data
    ports:
      - "${MATRIX_NEWS_WEBSOCKET_PORT:-10091}:10091"
    networks:
      - matrix_news_network
    depends_on:
      matrix-news-consciousness:
        condition: service_healthy
      matrix-redis:
        condition: service_healthy
    environment:
      - PORT=10091
      - REDIS_HOST=matrix-redis
      - REDIS_PORT=6379
      - NEWS_SERVICE_URL=http://matrix-news-consciousness:10090
      - PROPHECY_STREAM_ENABLED=true
      - QUANTUM_ENTROPY_LEVEL=8
      - FETCH_INTERVAL=60
      - LOG_LEVEL=INFO
      - NEWS_UPDATE_INTERVAL=300
      - BROADCAST_INTERVAL=30
      - MAX_RETRIES=3
      - RETRY_DELAY=5
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:10091/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped

  # Matrix Redis - Sacred State Memory
  matrix-redis:
    image: redis:6.2-alpine
    ports:
      - "${MATRIX_REDIS_PORT:-10379}:6379"
    volumes:
      - matrix_redis_data:/data
    networks:
      - matrix_news_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

networks:
  matrix_news_network:
    driver: bridge
  news_service_default:
    external: true

volumes:
  matrix_redis_data:
  consciousness_logs:
  consciousness_data:
  websocket_logs:
  websocket_data:
