groups:
  - name: divine_service_alerts
    rules:
      - alert: DivineServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Divine Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."

      - alert: DivineHighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "Service {{ $labels.job }} has CPU usage above 80% for more than 5 minutes."

      - alert: DivineHighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Service {{ $labels.job }} has memory usage above 80% for more than 5 minutes."

      # Divine High Disk Usage Alert
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High disk usage detected
          description: Disk usage is above 90% for 5 minutes

      # Divine High Error Rate Alert
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
          description: Error rate is above 5% for 5 minutes 