# 🔱 OMEGA BTC AI - SACRED ALERT MANAGER CONFIGURATION 🔱

global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/your/webhook/url'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@omega-btc-ai.com'
  smtp_auth_username: 'alerts@omega-btc-ai.com'
  smtp_auth_password: 'your_smtp_password'
  smtp_require_tls: true

# 🎭 Route Configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'divine-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'divine-critical'
      group_wait: 10s
      repeat_interval: 2h
    - match:
        severity: warning
      receiver: 'divine-warning'
      group_wait: 30s
      repeat_interval: 4h

# 📨 Receivers
receivers:
  - name: 'divine-notifications'
    email_configs:
      - to: 'alerts@omega-btc-ai.com'
        send_resolved: true
        html: |
          <h2>Divine Alert: {{ .GroupLabels.alertname }}</h2>
          <p><strong>Status:</strong> {{ .Status | toUpper }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>
          <p><strong>Details:</strong></p>
          <ul>
          {{ range .Alerts }}
            <li>
              <strong>Instance:</strong> {{ .Labels.instance }}<br>
              <strong>Service:</strong> {{ .Labels.service }}<br>
              <strong>Severity:</strong> {{ .Labels.severity }}<br>
              <strong>Started:</strong> {{ .StartsAt }}<br>
              {{ if .EndsAt }}<strong>Ended:</strong> {{ .EndsAt }}{{ end }}
            </li>
          {{ end }}
          </ul>

  - name: 'divine-critical'
    email_configs:
      - to: 'critical-alerts@omega-btc-ai.com'
        send_resolved: true
    slack_configs:
      - channel: '#divine-critical-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ .CommonLabels.grafana_url }}'
            style: '{{ if eq .Status "firing" }}danger{{ else }}default{{ end }}'
    telegram_configs:
      - bot_token: 'your_telegram_bot_token'
        chat_id: 123456789  # Replace with your actual chat ID as an integer
        parse_mode: 'HTML'
        message: |
          <b>🚨 Critical Alert: {{ .GroupLabels.alertname }}</b>
          <b>Status:</b> {{ .Status | toUpper }}
          <b>Description:</b> {{ .CommonAnnotations.description }}
          <b>Details:</b>
          {{ range .Alerts }}
          • Instance: {{ .Labels.instance }}
          • Service: {{ .Labels.service }}
          • Started: {{ .StartsAt }}
          {{ if .EndsAt }}• Ended: {{ .EndsAt }}{{ end }}
          {{ end }}

  - name: 'divine-warning'
    email_configs:
      - to: 'warnings@omega-btc-ai.com'
        send_resolved: true
    slack_configs:
      - channel: '#divine-warning-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ .CommonLabels.grafana_url }}'
            style: '{{ if eq .Status "firing" }}warning{{ else }}default{{ end }}'

# 🚨 Inhibition Rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# 📊 Templates
templates:
  - '/etc/alertmanager/template/*.tmpl' 