name: RASTA QA SHIELD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
        
    - name: JAH BLESS - Run Divine RASTA Tests
      run: |
        echo "🌿🔥 RUNNING DIVINE RASTA TEST SUITE 🔥🌿"
        python -m pytest omega_ai/tests/ --cov=omega_ai --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: RASTA-QA-SHIELD
        fail_ci_if_error: true
        
    - name: Generate Divine RASTA QA Badge
      if: success()
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: rasta-qa
        LABEL: 'JAH BLESS'
        STATUS: 'PASSED ✓'
        COLOR: 52b788
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}